[cdf]#<PLACEHOLDER>
default_env = "<DEFAULT_ENV_PLACEHOLDER>"

[modules]
# This is the version of the modules. It should not be changed manually.
# It will be updated by the 'cdf module upgrade' command.
version = "0.3.28"


[plugins]
run = true
pull = false
dump = false
