dev:
  name: dev
  project: <customer-dev>
  type: dev
  selected_modules_and_packages:
    - cdf_demo_infield
    - cdf_oid_example_data

prod:
  name: prod
  project: <customer-prod>
  type: prod
  selected_modules_and_packages:
    - cdf_infield
