environment:
  name: prod
  project: <my-project-prod>
  validation-type: prod
  selected:
  - modules/

variables:
  modules:
    dataset: ingestion
    instanceSpace: springfield_instances
    rawSourceDatabase: ingestion
    rawStateDatabase: contextualizationState
    annotationSpace: springfield_instances
    assetTransformationExternalId: sap_assets_springfield_s4hana
    equipmentTransformationExternalId: sap_equipment_springfield_s4hana
    equipmentToAssetTransformationExternalId: sap_equipment_to_asset_springfield_s4hana
    timeseriesTransformationExternalId: pi_timeseries_springfield_aveva_pi
    maintenanceOrderTransformationExternalId: sap_maintenance_orders_springfield_s4hana
    operationTransformationExternalId: sap_operations_springfield_s4hana
    operationToMaintenanceOrderTransformationExternalId: sap_operation_to_maintenance_order_springfield_s4hana
    fileTransformationExternalId: files_metadata_springfield
    activityToAssetTransformationExternalId: activity_to_asset
    activityToEquipmentTransformationExternalId: activity_to_equipment
    activityToTimeSeriesTransformationExternalId: activity_to_timeseries
    timeSeriesToAssetTransformationExternalId: timeseries_to_asset
    timeSeriesToEquipmentTransformationExternalId: timeseries_to_equipment
    organization: YourOrg
    cdf_common:
      directRelationJob: ctx_files_direct_relation_write
      rawStateTable: diagramParsing
      schemaSpace: cdf_cdm

    cdf_ingestion:
      workflow: ingestion
      groupSourceId: <not set>
      ingestionClientId: ${INGESTION_CLIENT_ID}
      ingestionClientSecret: ${INGESTION_CLIENT_SECRET}
      pandidContextualizationFunction: contextualization_p_and_id_annotater
      contextualization_connection_writer: contextualization_connection_writer
      schemaSpace: sp_enterprise_process_industry
      schemaSpace2: cdf_cdm
      schemaSpace3: cdf_idm
      instanceSpaces:
      - springfield_instances
      - cdf_cdm_units
      runWorkflowUserIds:
      - <your user id>

    contextualization:
      cdf_connection_sql:
        schemaSpace: cdf_cdm

      cdf_p_and_id_parser:
        contextualizationId: p_and_id_parser
        contextualizationName: P&ID Parser
        annotatorJob: ctx_files_pandid_annotater
        schemaSpace: cdf_cdm
        instanceSpaces:
        - springfield_instances

    industrial_tools:
      cdf_search:
        location: springfield
        locationName: Springfield

    models:
      cdf_process_industry_extension:
        schemaSpace: sp_enterprise_process_industry

    sourcesystem:
      cdf_pi:
        sourceName: Springfield AVEVA PI
        sourceId: springfield_aveva_pi
        schemaSpace: sp_enterprise_process_industry

      cdf_sap_assets:
        sourceName: SAP Springfield S/4HANA Assets
        sourceId: sap_springfield_s4hana_assets
        schemaSpace: sp_enterprise_process_industry

      cdf_sap_events:
        sourceName: SAP Springfield S/4HANA Activities
        sourceId: sap_springfield_s4hana_activities
        schemaSpace: sp_enterprise_process_industry

      cdf_sharepoint:
        sourceName: Springfield Sharepoint
        sourceId: springfield_sharepoint
        schemaSpace: sp_enterprise_process_industry
