sourceName: Springfield AVEVA PI
sourceId: springfield_aveva_pi # can also contain location, for example sap_springfield_s4hana
rawDatabase: aveva_pi_staging # can also contain location, for example aveva_pi_springfield_staging
transformationServicePrincipalGroupObjectId: <not set>
workflow: aveva_pi_population # can also contain location aveva_pi_springfield_population
dataset: aveva_pi_population # can also contain location aveva_pi_springfield_population
schemaSpace: cdf_cdm
instanceSpace: springfield_pi
