environment:
  name: dev
  project: infield-experimental-test-aws
  validation-type: dev
  selected:
    - modules/eriks-location

variables:
  modules:
    eriks-location:
      - location: tk_infield-cdm-v1
        location_name: Oslo CDM v1 + loc filter
        location_description: Used to test toolkit ingestion for InField cdm
